language: php

php:
  - '7.2'
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

#services:
#    - mysql

before_script:
  - composer install
#    - mysql -e 'create database dsql_test;'

after_script:
  - echo $TRAVIS_PHP_VERSION
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then echo "Sending codecov report"; bash <(curl -s https://codecov.io/bash); fi

script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.2" ]]; then NC="--no-coverage"; fi
  - ./vendor/phpunit/phpunit/phpunit $NC

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b33a2db0c636f34bafa9
      - https://webhooks.gitter.im/e/c4000ab24556b09cb3e7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

  slack:
    rooms:
      - agiletoolkit:bjrKuPBf1h4cYiNxPBQ1kF6c#dsql
    on_success: change

  email: false
